### ISSUE TITLE
Add license 

### ISSUE THREAD

**Issue by WeetHet** [orlp/glidesort#11]
Add some kind of license, so editing your repository and using it become legal

**Comment by orlp** [comment]
The license is specified in Cargo.toml, it's MIT OR Apache-2.0.

**Comment by WeetHet** [comment]
Don't you mind adding those as files?

**Comment by dreamlax** [comment]
I'm not a lawyer, so take my advice with a grain of salt, but I believe that the MIT license requires that you include an appropriate copyright notice as well as the permission notice itself. It is potentially not enough to simply say it is licensed under "MIT" because anyone who wants to use your code is required to display the same notices. If you haven't got these notices, I think people cannot use your code.
